import type { PermitStep } from '../types/permit';

export const PERMIT_STEPS: Omit<PermitStep, 'status' | 'vendors' | 'office' | 'agencies'>[] = [
  {
    id: 'site_review',
    order: 1,
    title: '사전 부지검토',
    type: 'self',
    estimatedDays: { min: 7, max: 28 },
    relation: 'sequential',
    criticalRisks: ['계통 불가 지역 진입 시 투자 전액 손실'],
    requiredDocuments: ['토지이음 열람 결과', '환경공간정보 결과', '등기부등본', '자치법규 검토'],
  },
  {
    id: 'power_license',
    order: 2,
    title: '발전사업허가',
    type: 'agency',
    estimatedDays: { min: 50, max: 90 },
    relation: 'independent_parallel',
    parallelWith: ['development_permit'],
    criticalRisks: ['허가 취득 후 3년 내 미착공 시 자동 취소'],
    requiredDocuments: [
      '발전사업허가 신청서',
      '사업계획서',
      '단선결선도',
      '발전원가명세서',
      '한전 접속 의향서',
      '재원조달계획서',
    ],
  },
  {
    id: 'development_permit',
    order: 3,
    title: '개발행위허가',
    type: 'office',
    estimatedDays: { min: 15, max: 730 },
    relation: 'independent_parallel',
    parallelWith: ['power_license', 'land_conversion', 'env_assessment'],
    criticalRisks: ['주민 반대 시 무기한 보류', '지자체 재량 광범위'],
    requiredDocuments: [
      '신청서',
      '형질변경 계획서',
      '토지 소유권 증명',
      '배치도',
      '구조계산서',
      '경관 심의 결과서',
    ],
  },
  {
    id: 'land_conversion',
    order: 4,
    title: '산지·농지전용',
    type: 'agency',
    estimatedDays: { min: 15, max: 60 },
    relation: 'parallel_possible',
    prerequisiteSteps: ['development_permit'],
    parallelWith: ['development_permit', 'env_assessment'],
    criticalRisks: [
      '보전산지·농업진흥구역 전용 불가',
      '복구비용 현금 예치 부담',
      '영농형 8년 만료 후 연장 불허 시 원상복구 의무',
    ],
    requiredDocuments: ['전용허가 신청서', '사업계획서', '복구계획서', '토지이용계획서'],
  },
  {
    id: 'env_assessment',
    order: 5,
    title: '환경영향평가',
    type: 'agency',
    estimatedDays: { min: 90, max: 365 },
    relation: 'parallel_possible',
    prerequisiteSteps: ['development_permit', 'land_conversion'],
    parallelWith: ['development_permit', 'land_conversion'],
    criticalRisks: [
      '생태·자연도 1~2등급 포함 시 협의 불가 → 사업 포기',
      '평가서 작성 비용 수천만~1억 원 이상',
    ],
    requiredDocuments: ['환경영향평가서', '생태자연도 조사', '주민 설명회 결과'],
  },
  {
    id: 'construction',
    order: 6,
    title: '공사계획 신고 및 시공',
    type: 'agency',
    estimatedDays: { min: 30, max: 180 },
    relation: 'sequential',
    prerequisiteSteps: ['power_license', 'development_permit', 'land_conversion', 'env_assessment'],
    criticalRisks: ['무면허 전기공사 시 준공검사 불가', '공사 중 주민 민원 → 공사 중단 명령'],
    requiredDocuments: ['공사계획 신고서', '착공 신고서', '시공 계획서', '감리 계획서'],
  },
  {
    id: 'grid_connection',
    order: 7,
    title: '계통연계 및 사용전검사',
    type: 'multi_agency',
    estimatedDays: { min: 90, max: 730 },
    relation: 'sequential',
    prerequisiteSteps: ['construction'],
    criticalRisks: [
      '선로 용량 부족 = 접속 불가 → 사업 좌초',
      'LVR 추가 비용 수천만~수억 원',
      'REC 설비 확인 1개월 기한 미준수 시 수익 소급 불가',
    ],
    requiredDocuments: ['계통 접속 신청서', '사용전검사 신청서', '전력거래 등록 서류', 'REC 설비 확인 서류'],
  },
];

export const PERMIT_STEP_ORDER: Record<string, number> = {
  site_review: 1,
  power_license: 2,
  development_permit: 3,
  land_conversion: 4,
  env_assessment: 5,
  construction: 6,
  grid_connection: 7,
};
