import type { Vendor, CivilOffice } from '../types/vendor';
import type { PermitStepId } from '../types/permit';

// ─── 인허가 업체 (단계별) ────────────────────────────────────────────────────

export const MOCK_VENDORS: Record<PermitStepId, Vendor[]> = {

  site_review: [
    {
      id: 'sr-1',
      name: '(주)솔라컨설팅그룹',
      successRate: 94,
      region: '전국',
      specialization: ['사전 부지검토', '토지이음 분석', '계통 접속 가능성 검토'],
      contactPhone: '02-3456-7890',
      isRecommended: true,
      responseHours: 4,
      userRating: 4.8,
      score: 96,
    },
    {
      id: 'sr-2',
      name: '에너지부지연구소',
      successRate: 89,
      region: '전국',
      specialization: ['입지 분석', '규제 사전 검토', '사업성 평가'],
      contactPhone: '031-234-5678',
      isRecommended: false,
      responseHours: 8,
      userRating: 4.4,
      score: 90,
    },
  ],

  power_license: [
    {
      id: 'pl-1',
      name: '(주)그린에너지파트너스',
      successRate: 91,
      region: '전국',
      specialization: ['발전사업허가', '전기사업법 대응', '산업통상자원부 인허가'],
      contactPhone: '02-5678-1234',
      isRecommended: true,
      responseHours: 6,
      userRating: 4.7,
      score: 93,
    },
    {
      id: 'pl-2',
      name: '솔라인허가컨설팅',
      successRate: 88,
      region: '전남·충남',
      specialization: ['발전사업허가', '한전 접속 의향서', '단선결선도 작성'],
      contactPhone: '061-987-6543',
      isRecommended: false,
      responseHours: 12,
      userRating: 4.3,
      score: 88,
    },
    {
      id: 'pl-3',
      name: '에너지법무그룹',
      successRate: 85,
      region: '전국',
      specialization: ['발전사업허가', '법무 자문', '분쟁 대응'],
      contactPhone: '02-1111-2222',
      isRecommended: false,
      responseHours: 24,
      userRating: 4.1,
      score: 85,
    },
    {
      id: 'pl-4',
      name: '(주)리뉴에너지컨설팅',
      successRate: 82,
      region: '경북·경남',
      specialization: ['발전사업허가', '재원조달계획', '사업계획서 작성'],
      contactPhone: '054-333-4444',
      isRecommended: false,
      responseHours: 10,
      userRating: 4.0,
      score: 82,
    },
  ],

  development_permit: [
    {
      id: 'dp-1',
      name: '(주)지평토목엔지니어링',
      successRate: 90,
      region: '전국',
      specialization: ['개발행위허가', '형질변경계획서', '경관심의 대응'],
      contactPhone: '02-9876-5432',
      isRecommended: true,
      responseHours: 8,
      userRating: 4.6,
      score: 92,
    },
    {
      id: 'dp-2',
      name: '한국토목컨설팅',
      successRate: 86,
      region: '전남·전북',
      specialization: ['개발행위허가', '토목설계', '지자체 협의'],
      contactPhone: '062-555-6789',
      isRecommended: false,
      responseHours: 12,
      userRating: 4.2,
      score: 86,
    },
  ],

  land_conversion: [
    {
      id: 'lc-1',
      name: '행정사법인 그린랜드',
      successRate: 93,
      region: '전국',
      specialization: ['농지전용허가', '산지전용허가', '복구계획서 작성'],
      contactPhone: '02-2222-3333',
      isRecommended: true,
      responseHours: 6,
      userRating: 4.8,
      score: 95,
    },
    {
      id: 'lc-2',
      name: '(주)토지컨설팅솔라',
      successRate: 89,
      region: '전남·충남',
      specialization: ['산지전용', '농업진흥구역 해제', '농지전용부담금 컨설팅'],
      contactPhone: '061-222-3333',
      isRecommended: false,
      responseHours: 10,
      userRating: 4.4,
      score: 89,
    },
    {
      id: 'lc-3',
      name: '행정사 박태양 사무소',
      successRate: 86,
      region: '경북·경남',
      specialization: ['농지전용', '임야 전용', '지목변경'],
      contactPhone: '053-444-5555',
      isRecommended: false,
      responseHours: 18,
      userRating: 4.1,
      score: 84,
    },
  ],

  env_assessment: [
    {
      id: 'ea-1',
      name: '(주)에코어스환경연구원',
      successRate: 87,
      region: '전국',
      specialization: ['환경영향평가', '생태자연도 조사', '주민설명회 운영'],
      contactPhone: '02-4444-5555',
      isRecommended: true,
      responseHours: 12,
      userRating: 4.5,
      score: 89,
    },
    {
      id: 'ea-2',
      name: '(주)그린환경컨설팅',
      successRate: 84,
      region: '전국',
      specialization: ['환경영향평가', '소규모 환경영향평가', '생태현황 조사'],
      contactPhone: '02-6666-7777',
      isRecommended: false,
      responseHours: 24,
      userRating: 4.2,
      score: 84,
    },
    {
      id: 'ea-3',
      name: '한국환경연구소(주)',
      successRate: 81,
      region: '전국',
      specialization: ['대형 환경영향평가', '수환경 조사', '대기·소음 조사'],
      contactPhone: '042-777-8888',
      isRecommended: false,
      responseHours: 48,
      userRating: 3.9,
      score: 80,
    },
  ],

  construction: [
    {
      id: 'ct-1',
      name: '(주)솔라텍코리아',
      successRate: 96,
      region: '전국',
      specialization: ['태양광 EPC 시공', '전력기기 설치', '준공검사 대응'],
      contactPhone: '02-8888-9999',
      isRecommended: true,
      responseHours: 4,
      userRating: 4.9,
      score: 97,
    },
    {
      id: 'ct-2',
      name: '(주)한양태양광시스템',
      successRate: 94,
      region: '전국',
      specialization: ['대형 태양광 시공', '수상태양광', '구조물 설계·시공'],
      contactPhone: '031-888-9999',
      isRecommended: false,
      responseHours: 6,
      userRating: 4.7,
      score: 94,
    },
    {
      id: 'ct-3',
      name: '(주)그린파워설비',
      successRate: 91,
      region: '전남·전북',
      specialization: ['중소형 태양광 시공', '농업형 태양광', '시공 감리'],
      contactPhone: '061-101-2020',
      isRecommended: false,
      responseHours: 8,
      userRating: 4.5,
      score: 91,
    },
    {
      id: 'ct-4',
      name: '(주)이노솔라',
      successRate: 88,
      region: '경북·충남',
      specialization: ['가성비 시공', '모듈 공급', '유지보수 계약'],
      contactPhone: '054-202-3030',
      isRecommended: false,
      responseHours: 10,
      userRating: 4.3,
      score: 87,
    },
  ],

  grid_connection: [
    {
      id: 'gc-1',
      name: '(주)켑코전기공사',
      successRate: 90,
      region: '전국',
      specialization: ['계통연계 공사', '한전 접속 신청 대행', 'REC 설비 확인'],
      contactPhone: '02-3030-4040',
      isRecommended: true,
      responseHours: 6,
      userRating: 4.6,
      score: 92,
    },
    {
      id: 'gc-2',
      name: '(주)태양전기연계',
      successRate: 87,
      region: '전남·경남',
      specialization: ['계통연계', 'KPX 전력거래 등록', 'REC 등록 대행'],
      contactPhone: '061-404-5050',
      isRecommended: false,
      responseHours: 10,
      userRating: 4.3,
      score: 87,
    },
    {
      id: 'gc-3',
      name: '(주)그리드커넥트',
      successRate: 85,
      region: '전국',
      specialization: ['154kV 이상 대용량 계통연계', '변전소 협의', 'LVR 설비'],
      contactPhone: '02-5050-6060',
      isRecommended: false,
      responseHours: 24,
      userRating: 4.1,
      score: 84,
    },
  ],
};

// ─── 토목사무소 (시·도별) ────────────────────────────────────────────────────

export const MOCK_OFFICES: Record<string, CivilOffice[]> = {

  '전라남도': [
    {
      id: 'off-jn-01',
      name: '나주종합토목사무소',
      address: '전남 나주시 빛가람로 272 (시청 앞 나주빌딩 3층)',
      phone: '061-331-1234',
      latitude: 35.0164,
      longitude: 126.7108,
      cityHall: '나주시청',
      permitExperienceCount: 134,
    },
    {
      id: 'off-jn-02',
      name: '영암토목건설사무소',
      address: '전남 영암군 영암읍 군청길 40 (군청 맞은편 2층)',
      phone: '061-470-2222',
      latitude: 34.8006,
      longitude: 126.6967,
      cityHall: '영암군청',
      permitExperienceCount: 98,
    },
    {
      id: 'off-jn-03',
      name: '해남군토목컨설팅',
      address: '전남 해남군 해남읍 중앙1로 33 (군청 인근)',
      phone: '061-530-3333',
      latitude: 34.5713,
      longitude: 126.5985,
      cityHall: '해남군청',
      permitExperienceCount: 87,
    },
    {
      id: 'off-jn-04',
      name: '신안종합개발사무소',
      address: '전남 신안군 안좌면 군청로 2 (군청 앞 1층)',
      phone: '061-240-4444',
      latitude: 34.8412,
      longitude: 126.3673,
      cityHall: '신안군청',
      permitExperienceCount: 71,
    },
    {
      id: 'off-jn-05',
      name: '영광토목개발',
      address: '전남 영광군 영광읍 군청길 12 (군청 앞 영광빌딩 2층)',
      phone: '061-350-5555',
      latitude: 35.2773,
      longitude: 126.5126,
      cityHall: '영광군청',
      permitExperienceCount: 62,
    },
    {
      id: 'off-jn-06',
      name: '고흥토목엔지니어링',
      address: '전남 고흥군 고흥읍 군청로 36 (군청 인근)',
      phone: '061-830-6666',
      latitude: 34.6022,
      longitude: 127.2786,
      cityHall: '고흥군청',
      permitExperienceCount: 54,
    },
  ],

  '충청남도': [
    {
      id: 'off-cn-01',
      name: '당진시종합토목사무소',
      address: '충남 당진시 시청1로 1 (시청 맞은편 3층)',
      phone: '041-350-1111',
      latitude: 37.0001,
      longitude: 126.6279,
      cityHall: '당진시청',
      permitExperienceCount: 112,
    },
    {
      id: 'off-cn-02',
      name: '태안군토목컨설팅',
      address: '충남 태안군 태안읍 군청로 1 (군청 인근 상가 2층)',
      phone: '041-670-2222',
      latitude: 36.7456,
      longitude: 126.2978,
      cityHall: '태안군청',
      permitExperienceCount: 75,
    },
    {
      id: 'off-cn-03',
      name: '서산토목개발사무소',
      address: '충남 서산시 시청로 1 (서산시청 앞 서산빌딩)',
      phone: '041-660-3333',
      latitude: 36.7845,
      longitude: 126.4503,
      cityHall: '서산시청',
      permitExperienceCount: 89,
    },
  ],

  '경상북도': [
    {
      id: 'off-kb-01',
      name: '경주시종합토목사무소',
      address: '경북 경주시 동문로 1 (시청 앞 경주타워 2층)',
      phone: '054-779-1111',
      latitude: 35.8562,
      longitude: 129.2247,
      cityHall: '경주시청',
      permitExperienceCount: 96,
    },
    {
      id: 'off-kb-02',
      name: '영덕군토목사무소',
      address: '경북 영덕군 영덕읍 군청길 30 (군청 인근)',
      phone: '054-730-2222',
      latitude: 36.4153,
      longitude: 129.3649,
      cityHall: '영덕군청',
      permitExperienceCount: 58,
    },
    {
      id: 'off-kb-03',
      name: '포항토목건설',
      address: '경북 포항시 남구 시청로 1 (시청 앞 포항빌딩 3층)',
      phone: '054-270-3333',
      latitude: 36.0190,
      longitude: 129.3435,
      cityHall: '포항시청',
      permitExperienceCount: 120,
    },
  ],

  '경상남도': [
    {
      id: 'off-kn-01',
      name: '밀양시토목사무소',
      address: '경남 밀양시 중앙로 3 (시청 인근 상가 2층)',
      phone: '055-359-1111',
      latitude: 35.5037,
      longitude: 128.7462,
      cityHall: '밀양시청',
      permitExperienceCount: 67,
    },
    {
      id: 'off-kn-02',
      name: '고성군토목컨설팅',
      address: '경남 고성군 고성읍 군청로 1 (군청 앞 1층)',
      phone: '055-670-2222',
      latitude: 34.9768,
      longitude: 128.3222,
      cityHall: '고성군청',
      permitExperienceCount: 49,
    },
    {
      id: 'off-kn-03',
      name: '함안종합토목사무소',
      address: '경남 함안군 가야읍 군청길 50 (군청 앞 2층)',
      phone: '055-580-3333',
      latitude: 35.2722,
      longitude: 128.4067,
      cityHall: '함안군청',
      permitExperienceCount: 53,
    },
  ],

  '전라북도': [
    {
      id: 'off-jb-01',
      name: '군산시종합토목사무소',
      address: '전북 군산시 시청로 17 (시청 앞 군산빌딩 3층)',
      phone: '063-454-1111',
      latitude: 35.9676,
      longitude: 126.7368,
      cityHall: '군산시청',
      permitExperienceCount: 82,
    },
    {
      id: 'off-jb-02',
      name: '정읍토목건설',
      address: '전북 정읍시 시청길 1 (시청 인근)',
      phone: '063-539-2222',
      latitude: 35.5695,
      longitude: 126.8558,
      cityHall: '정읍시청',
      permitExperienceCount: 61,
    },
    {
      id: 'off-jb-03',
      name: '고창군토목컨설팅',
      address: '전북 고창군 고창읍 군청길 17 (군청 앞 2층)',
      phone: '063-560-3333',
      latitude: 35.4349,
      longitude: 126.7017,
      cityHall: '고창군청',
      permitExperienceCount: 44,
    },
  ],

  '제주특별자치도': [
    {
      id: 'off-jj-01',
      name: '제주시토목종합사무소',
      address: '제주 제주시 문연로 6 (시청 앞 제주빌딩 2층)',
      phone: '064-728-1111',
      latitude: 33.4996,
      longitude: 126.5312,
      cityHall: '제주시청',
      permitExperienceCount: 108,
    },
    {
      id: 'off-jj-02',
      name: '서귀포토목사무소',
      address: '제주 서귀포시 중앙로 105 (시청 인근 서귀포빌딩)',
      phone: '064-760-2222',
      latitude: 33.2541,
      longitude: 126.5600,
      cityHall: '서귀포시청',
      permitExperienceCount: 76,
    },
  ],

  '강원도': [
    {
      id: 'off-gw-01',
      name: '강릉시토목건설',
      address: '강원 강릉시 강릉대로 33 (시청 앞 강릉빌딩 2층)',
      phone: '033-640-1111',
      latitude: 37.7519,
      longitude: 128.8760,
      cityHall: '강릉시청',
      permitExperienceCount: 71,
    },
    {
      id: 'off-gw-02',
      name: '원주토목사무소',
      address: '강원 원주시 시청로 1 (시청 인근)',
      phone: '033-737-2222',
      latitude: 37.3422,
      longitude: 127.9202,
      cityHall: '원주시청',
      permitExperienceCount: 60,
    },
  ],

  '경기도': [
    {
      id: 'off-gg-01',
      name: '화성시종합토목사무소',
      address: '경기 화성시 남양읍 시청로 159 (시청 앞 화성빌딩 3층)',
      phone: '031-369-1111',
      latitude: 37.1994,
      longitude: 126.8317,
      cityHall: '화성시청',
      permitExperienceCount: 143,
    },
    {
      id: 'off-gg-02',
      name: '안성토목개발',
      address: '경기 안성시 시청로 1 (시청 인근 안성빌딩 2층)',
      phone: '031-678-2222',
      latitude: 37.0078,
      longitude: 127.2797,
      cityHall: '안성시청',
      permitExperienceCount: 57,
    },
  ],
};

// ─── 헬퍼 함수 ────────────────────────────────────────────────────────────────

export function getVendorsByStep(stepId: PermitStepId): Vendor[] {
  return MOCK_VENDORS[stepId] ?? [];
}

export function getOfficesByProvince(province: string): CivilOffice[] {
  return MOCK_OFFICES[province] ?? [];
}
